export const MONSTER_MANUAL_URL =
  "https://raw.githubusercontent.com/TheGiddyLimit/homebrew/master/collection/Amellwind;%20Monster%20Hunter%20Monster%20Manual.json";

export const GUIDE_TO_MONSTER_HUNTING_URL =
  "https://raw.githubusercontent.com/TheGiddyLimit/homebrew/master/collection/Amellwind;%20Amellwind's%20Guide%20to%20Monster%20Hunting.json";

/** Tiempo de caché en milisegundos: 24 horas */
export const CACHE_TTL_MS = 24 * 60 * 60 * 1000;

export const DB_NAME = "mh-dnd5e-toolbox";
export const DB_VERSION = 1;

export const STORES = {
  MM_CURRENT: "mm_current",
  MM_PREVIOUS: "mm_previous",
  MM_META: "mm_meta",
  GTMH_CURRENT: "gtmh_current",
  GTMH_PREVIOUS: "gtmh_previous",
  GTMH_META: "gtmh_meta",
} as const;

export const FIVETOOLS_DATA_BASE_URL =
  "https://raw.githubusercontent.com/5etools-mirror-3/5etools-src/main/data";

export const SPELLS_BASE_URL = `${FIVETOOLS_DATA_BASE_URL}/spells`;

export const BOOKS_JSON_URL = `${FIVETOOLS_DATA_BASE_URL}/books.json`;

/** Generated by 5etools from spells/sources.json + class additionalSpells */
export const SPELL_SOURCE_LOOKUP_URL =
  "https://raw.githubusercontent.com/5etools-mirror-3/5etools-src/main/data/generated/gendata-spell-source-lookup.json";

export const SPELL_SOURCE_FILES: Record<string, string> = {
  PHB: "spells-phb.json",
  XPHB: "spells-xphb.json",
  XGE: "spells-xge.json",
  TCE: "spells-tce.json",
  FRHoF: "spells-frhof.json",
  EGW: "spells-egw.json",
  FTD: "spells-ftd.json",
  AI: "spells-ai.json",
  SCC: "spells-scc.json",
  LLK: "spells-llk.json",
  BMT: "spells-bmt.json",
  "AitFR-AVT": "spells-aitfr-avt.json",
  AAG: "spells-aag.json",
  GGR: "spells-ggr.json",
  IDRotF: "spells-idrotf.json",
  SatO: "spells-sato.json",
  EFA: "spells-efa.json",
};
