export const MONSTER_MANUAL_URL =
  "https://raw.githubusercontent.com/TheGiddyLimit/homebrew/master/collection/Amellwind;%20Monster%20Hunter%20Monster%20Manual.json";

export const GUIDE_TO_MONSTER_HUNTING_URL =
  "https://raw.githubusercontent.com/TheGiddyLimit/homebrew/master/collection/Amellwind;%20Amellwind's%20Guide%20to%20Monster%20Hunting.json";

/** Tiempo de caché en milisegundos: 24 horas */
export const CACHE_TTL_MS = 24 * 60 * 60 * 1000;

export const DB_NAME = "mh-dnd5e-toolbox";
export const DB_VERSION = 1;

export const STORES = {
  MM_CURRENT: "mm_current",
  MM_PREVIOUS: "mm_previous",
  MM_META: "mm_meta",
  GTMH_CURRENT: "gtmh_current",
  GTMH_PREVIOUS: "gtmh_previous",
  GTMH_META: "gtmh_meta",
} as const;

export const FIVETOOLS_DATA_BASE_URL =
  "https://raw.githubusercontent.com/5etools-mirror-3/5etools-src/main/data";

export const SPELLS_BASE_URL = `${FIVETOOLS_DATA_BASE_URL}/spells`;

/**
 * 5etools class JSONs live under data/class/ in the repo:
 * https://github.com/5etools-mirror-3/5etools-src/tree/main/data/class
 *
 * For fetch() we use raw.githubusercontent.com (not github.com/tree or /blob URLs).
 * Example: CLASSES_BASE_URL + "/class-artificer.json"
 *   → https://raw.githubusercontent.com/5etools-mirror-3/5etools-src/main/data/class/class-artificer.json
 */
export const CLASSES_BASE_URL = `${FIVETOOLS_DATA_BASE_URL}/class`;

/** Mirrors data/class/index.json — one JSON file per base class */
export const CLASS_SOURCE_FILES: Record<string, string> = {
  artificer: "class-artificer.json",
  barbarian: "class-barbarian.json",
  bard: "class-bard.json",
  cleric: "class-cleric.json",
  druid: "class-druid.json",
  fighter: "class-fighter.json",
  monk: "class-monk.json",
  mystic: "class-mystic.json",
  paladin: "class-paladin.json",
  ranger: "class-ranger.json",
  rogue: "class-rogue.json",
  sidekick: "class-sidekick.json",
  sorcerer: "class-sorcerer.json",
  warlock: "class-warlock.json",
  wizard: "class-wizard.json",
};

export const CLASS_INDEX_URL = `${CLASSES_BASE_URL}/index.json`;

/** Generated by 5etools for subclass display names and reprints */
export const SUBCLASS_LOOKUP_URL = `${FIVETOOLS_DATA_BASE_URL}/generated/gendata-subclass-lookup.json`;

export const BOOKS_JSON_URL = `${FIVETOOLS_DATA_BASE_URL}/books.json`;

/** Adventure catalog (source/id → display name). Local dev: copy to public/5etools/adventures.json */
export const ADVENTURES_JSON_URL = `${FIVETOOLS_DATA_BASE_URL}/adventures.json`;

/** Generated by 5etools from spells/sources.json + class additionalSpells */
export const SPELL_SOURCE_LOOKUP_URL =
  "https://raw.githubusercontent.com/5etools-mirror-3/5etools-src/main/data/generated/gendata-spell-source-lookup.json";

/** 5etools item compendium (single-file + base + magic variants). Local dev: copy backup-jsons/5etools/*.json → public/5etools/ and set VITE_5ETOOLS_DATA=local */
export const ITEMS_JSON_URL = `${FIVETOOLS_DATA_BASE_URL}/items.json`;
export const ITEMS_BASE_JSON_URL = `${FIVETOOLS_DATA_BASE_URL}/items-base.json`;
export const MAGIC_VARIANTS_JSON_URL = `${FIVETOOLS_DATA_BASE_URL}/magicvariants.json`;
export const LOCAL_5ETOOLS_BASE = "/5etools";

/** Bestiary compendium — local dev: copy backup-jsons/5etools/bestiary/ → public/5etools/bestiary/; set VITE_5ETOOLS_DATA=local. Minimum: index.json, bestiary-mm.json, legendarygroups.json */
export const BESTIARY_BASE_URL = `${FIVETOOLS_DATA_BASE_URL}/bestiary`;
export const BESTIARY_INDEX_URL = `${BESTIARY_BASE_URL}/index.json`;
export const LEGENDARY_GROUPS_URL = `${BESTIARY_BASE_URL}/legendarygroups.json`;

/** Fuentes precargadas al abrir el bestiario; el resto se cargan bajo demanda */
export const DEFAULT_BESTIARY_SOURCES = ["MM", "VGM", "MPMM", "XMM"] as const;

/** Fuentes precargadas al abrir ítems D&D (PHB/DMG 2014 y 2024); el resto bajo demanda */
export const DEFAULT_DND_ITEM_SOURCES = ["PHB", "XPHB", "DMG", "XDMG"] as const;

export const SPELL_SOURCE_FILES: Record<string, string> = {
  PHB: "spells-phb.json",
  XPHB: "spells-xphb.json",
  XGE: "spells-xge.json",
  TCE: "spells-tce.json",
  FRHoF: "spells-frhof.json",
  EGW: "spells-egw.json",
  FTD: "spells-ftd.json",
  AI: "spells-ai.json",
  SCC: "spells-scc.json",
  LLK: "spells-llk.json",
  BMT: "spells-bmt.json",
  "AitFR-AVT": "spells-aitfr-avt.json",
  AAG: "spells-aag.json",
  GGR: "spells-ggr.json",
  IDRotF: "spells-idrotf.json",
  SatO: "spells-sato.json",
  EFA: "spells-efa.json",
};
