/**
 * Upstream update feeds (GitHub).
 *
 * IMPORTANT: GitHub is only an *update feed*. At runtime the app's own
 * IndexedDB stores are the source of truth; these URLs are used solely to
 * refresh those stores in the background (see `fivetools-fetch.ts` and
 * `sync.service.ts`). See README → "Fuentes de datos".
 *
 * The mirror/homebrew repo slug and git ref are overridable via env vars, so a
 * 5etools mirror rotation (e.g. `5etools-mirror-3` → `-4`) or a fork can be
 * pointed at without touching source — just set the var and redeploy.
 */
const GITHUB_RAW = "https://raw.githubusercontent.com";

/** 5etools compendium mirror. Override: VITE_5ETOOLS_MIRROR / VITE_5ETOOLS_REF. */
const FIVETOOLS_MIRROR =
  import.meta.env.VITE_5ETOOLS_MIRROR ?? "5etools-mirror-3/5etools-src";
const FIVETOOLS_REF = import.meta.env.VITE_5ETOOLS_REF ?? "main";

/** Amellwind homebrew feed. Override: VITE_HOMEBREW_MIRROR / VITE_HOMEBREW_REF. */
const HOMEBREW_MIRROR =
  import.meta.env.VITE_HOMEBREW_MIRROR ?? "TheGiddyLimit/homebrew";
const HOMEBREW_REF = import.meta.env.VITE_HOMEBREW_REF ?? "master";

/** Unearthed Arcana / prerelease feed. Override: VITE_UA_MIRROR / VITE_UA_REF. */
const UA_MIRROR =
  import.meta.env.VITE_UA_MIRROR ?? "TheGiddyLimit/unearthed-arcana";
const UA_REF = import.meta.env.VITE_UA_REF ?? "master";

export const HOMEBREW_BASE_URL = `${GITHUB_RAW}/${HOMEBREW_MIRROR}/${HOMEBREW_REF}`;
const HOMEBREW_COLLECTION_BASE = `${HOMEBREW_BASE_URL}/collection`;
export const UA_BASE_URL = `${GITHUB_RAW}/${UA_MIRROR}/${UA_REF}`;

/** Amellwind Monster Hunter Monster Manual (homebrew). */
export const MONSTER_MANUAL_URL = `${HOMEBREW_COLLECTION_BASE}/Amellwind;%20Monster%20Hunter%20Monster%20Manual.json`;

/** Amellwind's Guide to Monster Hunting (homebrew): items, species, backgrounds, feats, MH classes, class features, weapon optional features and variant rules. */
export const GUIDE_TO_MONSTER_HUNTING_URL = `${HOMEBREW_COLLECTION_BASE}/Amellwind;%20Amellwind's%20Guide%20to%20Monster%20Hunting.json`;

/**
 * Cache freshness window (ms): 24h. Past this, stored data is still served
 * immediately (offline-first) and refreshed from the feed in the background.
 */
export const CACHE_TTL_MS = 24 * 60 * 60 * 1000;

export const DB_NAME = "mh-dnd5e-toolbox";
// v2: adds the additive `fivetools_cache` store (persists the 5etools compendium).
// The upgrade only creates missing stores, so existing mm_*/gtmh_* data is
// preserved intact when migrating v1 → v2.
export const DB_VERSION = 2;

export const STORES = {
  MM_CURRENT: "mm_current",
  MM_PREVIOUS: "mm_previous",
  MM_META: "mm_meta",
  GTMH_CURRENT: "gtmh_current",
  GTMH_PREVIOUS: "gtmh_previous",
  GTMH_META: "gtmh_meta",
  /** Read-through cache for the 5etools compendium (source of truth for offline use). */
  FIVETOOLS_CACHE: "fivetools_cache",
} as const;

export const FIVETOOLS_DATA_BASE_URL = `${GITHUB_RAW}/${FIVETOOLS_MIRROR}/${FIVETOOLS_REF}/data`;

export const SPELLS_BASE_URL = `${FIVETOOLS_DATA_BASE_URL}/spells`;
export const SPELL_INDEX_URL = `${SPELLS_BASE_URL}/index.json`;
/** Index of per-source spell fluff files under data/spells/ (spellFluff + art). */
export const SPELL_FLUFF_INDEX_URL = `${SPELLS_BASE_URL}/fluff-index.json`;

/**
 * 5etools class JSONs live under data/class/ in the mirror, one file per base
 * class. Fetched via raw.githubusercontent.com (derived from
 * FIVETOOLS_DATA_BASE_URL). Example: `${CLASSES_BASE_URL}/class-artificer.json`.
 */
export const CLASSES_BASE_URL = `${FIVETOOLS_DATA_BASE_URL}/class`;

export const CLASS_INDEX_URL = `${CLASSES_BASE_URL}/index.json`;

/** UA/prerelease generated indexes (TheGiddyLimit/unearthed-arcana). */
export const UA_INDEX_SOURCES_URL = `${UA_BASE_URL}/_generated/index-sources.json`;
export const UA_INDEX_META_URL = `${UA_BASE_URL}/_generated/index-meta.json`;
export const UA_INDEX_TIMESTAMPS_URL = `${UA_BASE_URL}/_generated/index-timestamps.json`;

/**
 * Partnered 3rd-party brew indexes (TheGiddyLimit/homebrew).
 * Meta flag `p: 1` marks partnered sources (same set as 5etools
 * `search/index-partnered.json`).
 */
export const HOMEBREW_INDEX_SOURCES_URL = `${HOMEBREW_BASE_URL}/_generated/index-sources.json`;
export const HOMEBREW_INDEX_META_URL = `${HOMEBREW_BASE_URL}/_generated/index-meta.json`;
export const HOMEBREW_INDEX_TIMESTAMPS_URL = `${HOMEBREW_BASE_URL}/_generated/index-timestamps.json`;

/** Generated by 5etools for subclass display names and reprints */
export const SUBCLASS_LOOKUP_URL = `${FIVETOOLS_DATA_BASE_URL}/generated/gendata-subclass-lookup.json`;

export const BOOKS_JSON_URL = `${FIVETOOLS_DATA_BASE_URL}/books.json`;

/** Adventure catalog (source/id → display name). Local dev: copy to public/5etools/adventures.json */
export const ADVENTURES_JSON_URL = `${FIVETOOLS_DATA_BASE_URL}/adventures.json`;

/** Generated by 5etools from spells/sources.json + class additionalSpells */
export const SPELL_SOURCE_LOOKUP_URL = `${FIVETOOLS_DATA_BASE_URL}/generated/gendata-spell-source-lookup.json`;

/** 5etools races/species compendium. Local dev: copy backup-jsons/5etools/races.json → public/5etools/races.json and set VITE_5ETOOLS_DATA=local */
export const RACES_JSON_URL = `${FIVETOOLS_DATA_BASE_URL}/races.json`;
/** Parallel fluff file for races/species (lore + art). Local: fluff-races.json */
export const FLUFF_RACES_JSON_URL = `${FIVETOOLS_DATA_BASE_URL}/fluff-races.json`;

/** Index of per-class fluff files under data/class/ (classFluff + subclassFluff). */
export const CLASS_FLUFF_INDEX_URL = `${CLASSES_BASE_URL}/fluff-index.json`;

/** 5etools backgrounds compendium. Local dev: copy backup-jsons/5etools/backgrounds.json + fluff-backgrounds.json → public/5etools/ and set VITE_5ETOOLS_DATA=local */
export const BACKGROUNDS_JSON_URL = `${FIVETOOLS_DATA_BASE_URL}/backgrounds.json`;
export const FLUFF_BACKGROUNDS_JSON_URL = `${FIVETOOLS_DATA_BASE_URL}/fluff-backgrounds.json`;

/** 5etools feats compendium. Local dev: copy backup-jsons/5etools/feats.json + fluff-feats.json → public/5etools/ and set VITE_5ETOOLS_DATA=local */
export const FEATS_JSON_URL = `${FIVETOOLS_DATA_BASE_URL}/feats.json`;
export const FLUFF_FEATS_JSON_URL = `${FIVETOOLS_DATA_BASE_URL}/fluff-feats.json`;

/** 5etools optional features (EI, Metamagic, Maneuvers, …). Local dev: copy optionalfeatures.json → public/5etools/ */
export const OPTIONALFEATURES_JSON_URL = `${FIVETOOLS_DATA_BASE_URL}/optionalfeatures.json`;

/** 5etools languages compendium. Local dev: copy backup-jsons/5etools/languages.json → public/5etools/ and set VITE_5ETOOLS_DATA=local */
export const LANGUAGES_JSON_URL = `${FIVETOOLS_DATA_BASE_URL}/languages.json`;

/** 5etools species name tables (XGE). Local dev: copy backup-jsons/5etools/names.json → public/5etools/ */
export const NAMES_JSON_URL = `${FIVETOOLS_DATA_BASE_URL}/names.json`;

/** 5etools item compendium (single-file + base + magic variants). Local dev: copy backup-jsons/5etools/*.json → public/5etools/ and set VITE_5ETOOLS_DATA=local */
export const ITEMS_JSON_URL = `${FIVETOOLS_DATA_BASE_URL}/items.json`;
export const ITEMS_BASE_JSON_URL = `${FIVETOOLS_DATA_BASE_URL}/items-base.json`;
export const MAGIC_VARIANTS_JSON_URL = `${FIVETOOLS_DATA_BASE_URL}/magicvariants.json`;
/** Parallel fluff file for items (lore + art). Local: fluff-items.json */
export const FLUFF_ITEMS_JSON_URL = `${FIVETOOLS_DATA_BASE_URL}/fluff-items.json`;
export const LOCAL_5ETOOLS_BASE = "/5etools";

/** Bestiary compendium — local dev: copy backup-jsons/5etools/bestiary/ → public/5etools/bestiary/; set VITE_5ETOOLS_DATA=local. Minimum: index.json, bestiary-mm.json, legendarygroups.json */
export const BESTIARY_BASE_URL = `${FIVETOOLS_DATA_BASE_URL}/bestiary`;
export const BESTIARY_INDEX_URL = `${BESTIARY_BASE_URL}/index.json`;
export const LEGENDARY_GROUPS_URL = `${BESTIARY_BASE_URL}/legendarygroups.json`;

/** Sources preloaded when the bestiary opens; the rest load on demand. */
export const DEFAULT_BESTIARY_SOURCES = ["MM", "VGM", "MPMM", "XMM"] as const;

/** Sources preloaded when D&D items open (PHB/DMG 2014 and 2024); the rest on demand. */
export const DEFAULT_DND_ITEM_SOURCES = ["PHB", "XPHB", "DMG", "XDMG"] as const;

/** D&D Beyond exclusive residual that ships in the UA feed (not scraped from DDB). */
export const DDB_SOURCE_CODES = ["WGE"] as const;
