/** @deprecated Import from `@/shared/foundry` instead. */
export {
  slugify,
  kebab,
  mapDamageType,
  mapWeaponProperty,
  parseWeaponRange,
  mapAmmunitionType,
  mapWeaponTypeValue,
  mapArmorTypeValue,
  mapSize,
  mapLanguage,
  mapTool,
  toolAbility,
  mapWeaponProficiency,
  mapArmorProficiency,
  mapCasterProgression,
  mapAbilityLabel,
  mapRarity,
  FULL_CASTER_SLOTS,
  PACT_MAGIC_TABLE,
  effectiveCasterLevel,
} from "@/shared/foundry";
