/** Compact lookup generated by 5etools `node/generate-spell-source-lookup.js` */
export type SpellClassLookupValue =
  | true
  | { definedInSource?: string; definedInSources?: (string | null)[] };

export type SpellSubclassLookupValue = {
  name: string;
  subSubclasses?: string[];
};

export type SpellSourceLookupEntry = {
  class?: Record<string, Record<string, SpellClassLookupValue>>;
  classVariant?: Record<string, Record<string, SpellClassLookupValue>>;
  subclass?: Record<
    string,
    Record<string, Record<string, Record<string, SpellSubclassLookupValue>>>
  >;
};

export type SpellSourceLookup = Record<
  string,
  Record<string, SpellSourceLookupEntry>
>;
